version: "3"

services:
  makemkv:
    image: hydrohs/makemkv
    container_name: makemkv
    ports:
      - "2200:22"
      - "10000:10000"
    volumes:
      - ~/.ssh/authorized_keys:/authorized_keys:ro
      - config:/config
      - /storage:/storage
      - /output:/output
    environment:
      - AUTO_DISC_RIPPER=1
      - AUTO_DISC_RIPPER_EJECT=1
      - AUTO_DISC_RIPPER_MIN_TITLE_LENGTH=120
    env_file:
      - .env
    devices:
      - /dev/sr1
      - /dev/sg10
    restart: unless-stopped

volumes:
  config:
