version: "3"

services:
  makemkv:
    build: .
    container_name: makemkv
    ports:
      - "2200:2200"
      - "10000:10000"
    volumes:
      - ~/.ssh/authorized_keys:/authorized_keys:ro
      - config:/config
      - /data/hydrohs:/storage
      - /data/hydrohs/ripped:/output
    environment:
      - AUTO_DISC_RIPPER=0
      - AUTO_DISC_RIPPER_EJECT=1
      - AUTO_DISC_RIPPER_MIN_TITLE_LENGTH=120

volumes:
  config:
